# Generated by Django 4.2.6 on 2023-10-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sebo_de_discos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeloFonografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('idade', models.PositiveIntegerField()),
                ('discos', models.ManyToManyField(to='sebo_de_discos.disco')),
            ],
        ),
        migrations.AlterField(
            model_name='disco',
            name='selo_fonografico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sebo_de_discos.selofonografico'),
        ),
    ]
