# Generated by Django 4.2.6 on 2023-10-26 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sebo_de_discos', '0002_selofonografico_artista_alter_disco_selo_fonografico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='discos',
        ),
        migrations.AddField(
            model_name='disco',
            name='artistas',
            field=models.ManyToManyField(to='sebo_de_discos.artista'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='selo_fonografico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discos', to='sebo_de_discos.selofonografico'),
        ),
    ]
